[package]
name = "macro-test"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "attributes"
]

[dependencies]
syn = {version = "1.0.91", features = ["full"]}
quote = "1.0.18"
attributes = {path = "attributes" }
